name: Learn Github Packaging
on: [push]
jobs:
  version:2
  build:
    os: "ubuntu-22.04"
    tools:
      python: "3.11"
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Packaging citylocations for release!

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
